import { PizzaIcon } from "lucide-react";

const burgerData = [
  {
    id: 1,
    ref: "00001",
    name: "Burger 01",
    price: 10.0,
    img: "02.png",
    option: "with fries",
    categoryId: 2, 
  },
  {
    id: 2,
    ref: "00002",
    name: "Burger 02",
    price: 11.0,
    img: "02.png",
    option: "with cheese",
    categoryId: 2, 
  },
  {
    id: 3,
    ref: "00003",
    name: "Burger 03",
    price: 12.0,
    img: "02.png",
    option: "with bacon",
    categoryId: 2, 
  },
  {
    id: 4,
    ref: "00004",
    name: "Burger 04",
    price: 13.0,
    img: "02.png",
    option: "with avocado",
    categoryId: 2, 
  },
  {
    id: 5,
    ref: "00005",
    name: "Burger 05",
    price: 14.0,
    img: "02.png",
    option: "with spicy sauce",
    categoryId: 2, 
  },
  {
    id: 6,
    ref: "00006",
    name: "Tacos 01",
    price: 10.0,
    img: "01.png",
    option: "with fries",
    categoryId: 3, 
  },
  {
    id: 7,
    ref: "00007",
    name: "Tacos 02",
    price: 11.0,
    img: "01.png",
    option: "with guacamole",
    categoryId: 3,
  },
  {
    id: 8,
    ref: "00008",
    name: "Tacos 03",
    price: 12.0,
    img: "01.png",
    option: "with extra cheese",
    categoryId: 3, 
  },
  {
    id: 9,
    ref: "00009",
    name: "Pizza 01",
    price: 12.0,
    img: "02.png",
    option: "with extra cheese",
    categoryId: 1, 
  },
  {
    id: 10,
    ref: "00010",
    name: "Pizza 02",
    price: 13.0,
    img: "02.png",
    option: "with pepperoni",
    categoryId: 1, 
  },
  {
    id: 11,
    ref: "00011",
    name: "Pizza 03",
    price: 14.0,
    img: "02.png",
    option: "with vegetables",
    categoryId: 1, 
  },
  
  {
    id: 12,
    ref: "00012",
    name: "Salad 01",
    price: 8.0,
    img: "03.png",
    option: "with dressing",
    categoryId: 4, 
  },
  {
    id: 13,
    ref: "00013",
    name: "Salad 02",
    price: 9.0,
    img: "03.png",
    option: "with croutons",
    categoryId: 4,
  },
  {
    id: 14,
    ref: "00014",
    name: "Dessert 01",
    price: 5.0,
    img: "04.png",
    option: "with chocolate",
    categoryId: 5, 
  },
  {
    id: 17,
    ref: "00015",
    name: "Dessert 02",
    price: 6.0,
    img: "04.png",
    option: "with fruits",
    categoryId: 5, 
  },
];

const categoryData = [
  {
    id: 1,
    name: "pizza",
    icon: <PizzaIcon />,
  },
  {
    id: 2,
    name: "burger",
    icon: <PizzaIcon />,
  },
  {
    id: 3,
    name: "tacos",
    icon: <PizzaIcon />,
  },
  {
    id: 4,
    name: "salad",
    icon: <PizzaIcon />, 
  },
  {
    id: 5,
    name: "dessert",
    icon: <PizzaIcon />, 
  },
];

export default burgerData;
export { categoryData };
